name: qarz_v2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
#  http: ^1.3.0
#  shared_preferences: ^2.5.2
  intl: ^0.20.2
  http: ^1.3.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  pocketbase: ^0.22.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
     - assets/images/
